### ISSUE TITLE
Teradata Conversion Failing with unsupported features

### ISSUE THREAD

**Issue by elZagales** [google/dwh-migration-tools#46]
When executing the dw-migration-client with metadata generated by dwh-migration-dumper the following errors are produced in the batch_translation_report.csv:

BigQuery does not support INDEX-backed constraints such as PRIMARY KEY and UNIQUE.
BigQuery does not support set tables.
BigQuery cluster-expression 'dataparcel' is of unsupported type VARBINARY
BigQuery cluster-expression 'pnch_in_tim' is of unsupported type TIME
BigQuery cluster-expression 'txn_tim' is of unsupported type TIME
BigQuery does not support more than 4 CLUSTER BY expressions, got X
Unsupported RANGE partition: RANGE partition supported only for Integers. Using auto partitioning for DATE

Ideally these conflicts would be automatically resolved for example:
Removal of Primary and Unique keys definitions
Remove qualifiers for set and multiset in ddl
Reducing clustered fields to the limit
Removing unsupported partition definitions

**Comment by genemerrill** [comment]
Thanks for your feedback. Many of these should be considered warnings rather than errors. We may want to adjust how we categorize the report log entries to help customers understand what is actionable and what is not.


> BigQuery does not support INDEX-backed constraints such as PRIMARY KEY and UNIQUE.

The translator should already be removing/commenting these lines, what you are seeing is a warning to the user.

> BigQuery does not support set tables.

Another warning for the user. The translated output will not contain any Teradata-specific syntax like `SET` or `MULTISET` but when metadata coverage is available will translate `INSERT` statements into `MERGE` using `WHEN MATCHED / WHEN NOT MATCHED` logic to emulate the source dialect behavior. (The benefit of using a true compiler to translate rather than pattern matching!)

> BigQuery does not support more than 4 CLUSTER BY expressions, got X

This is a warning to the user, we should be limiting to four in the translated SQL already.

But if any of the above doesn't match what you are experiencing please first check for RelationNotFound and AttributeNotFound issues with the objects used by the SQL in question to validate metadata coverage. If no issues there, then provide input examples and some guidance on what you would expect in the translated results. We are always improving the translation engine and this type of feedback is very helpful.

And that still leaves us with the unsupported types in cluster-expression, and the Unsupported RANGE partition. I've filed these with engineering and if you can provide any sample input (even if just generic) and guidance on output that would work for your use-case, it would be appreciated.
